### ISSUE TITLE
missing dependencies in python:14.3-lts

### ISSUE THREAD

**Issue by ericfeunekes** [databricks/containers#188]
I used the `databricksruntime/python:14.3-LTS` image but when loading it in Databricks it's missing some dependencies for IPywidgets. As well as the dependencies for Black formatting to work. 

Regarding the former. I tried using `tqdm` but it fails, saying I need to update jupyter and ipywidgets. So I pip install those. Then when I try running `tqdm` it just says that it fails to load. 

I haven't tried installing the dependencies for black formatting yet. 

This is mostly to say I understand you want a minimal version for the python image (from comments on #150), but it would be good if it at least allowed the image to work with Databricks features. I'm not sure what libraries I'd have to install in my custom image to make sure all Databricks features work.

**Comment by xinzhao-db** [comment]
@joveyuan-db Can you take a look?

Btw, starting from 15.4, we install the same set of python dependencies as DBR in DCS

**Comment by joveyuan-db** [comment]
Hi @ericfeunekes, as @xinzhao-db mentioned, DCS images corresponding to DBR 14.3 and older had a more minimal set of Python dependencies and did not necessarily support all Databricks features out of the box.  You should be able to install the missing ones manually to get the expected behavior though.  Could you share an example of what error you're seeing when trying to run `tqdm`?

**Comment by ericfeunekes** [comment]
Sorry this is pretty old now. I don't remember what I was doing at the time anymore. Nice to hear there's a full install now though!

**Comment by joveyuan-db** [comment]
No worries, thanks!
