### ISSUE TITLE
python:9.x is version 3.8.0 but python-conda:9.x is 3.8.5

### ISSUE THREAD

**Issue by iantheparker** [databricks/containers#62]
Not a big deal - I'm happy to leave conda behind and go with the default recipe, but .0 versions are buggier and 3.8.5 is closer to what's actually in the [databricks 8.4 runtime now](https://docs.databricks.com/release-notes/runtime/8.4.html#system-environment). 

It's a pain pulling a specific version without building from source, but just putting this here in case you'd advise sticking to python-conda for now.

**Comment by iantheparker** [comment]
Also, I'm seeing this error
```
Python in worker has different version 3.8 than that in driver 3.6, PySpark cannot run with different minor versions. Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set. 
```
Was `PYSPARK_DRIVER_PYTHON` previously set in the conda environment and it needs to be set in these too?

**Comment by shanelanan** [comment]
What is the nomenclature for these images to follow?

7.X image ran for a 7.X runtime which had python 3.7.

Now dockerhub has both a 8.X and a 9.X image, both using python 3.8.

Can someone please explain what is is the correct image to use to simulate a 8.4 runtime?

**Comment by vperiyasamy** [comment]
@iantheparker as you mentioned, it's a bit painful to specify micro versions without building from source. Because these images are based off of Ubuntu 18.04, the default python 3.8 installed in `3.8.0`. Since this is an example recipe, we'd recommend you update the recipe to build from source or use the Conda recipe if that's a requirement for you. Once we update these to build from Ubuntu 20.04, we'll have more flexibility (currently installing `python3` gives `3.8.10` on that OS).

@shanelanan we removed the `latest` tags to remove ambiguity around which images should be used with which runtimes, i.e. for 8.4 you should use `8.x`.

**Comment by vperiyasamy** [comment]
Closing this issue, but if you have any more questions let me know!

**Comment by iantheparker** [comment]
> @iantheparker as you mentioned, it's a bit painful to specify micro versions without building from source. Because these images are based off of Ubuntu 18.04, the default python 3.8 installed is `3.8.0`. Since this is an example recipe, we'd recommend you update the recipe to build from source or use the Conda recipe if that's a requirement for you. Once we update these to build from Ubuntu 20.04, we'll have more flexibility (currently installing `python3` gives `3.8.10` on that OS).
> 
> @shanelanan we removed the `latest` tags to remove ambiguity around which images should be used with which runtimes, i.e. for 8.4 you should use `8.x`.

@vperiyasamy Just curious, what's keeping you from moving to ubuntu 20.04 and jdk11?

**Comment by vperiyasamy** [comment]
@iantheparker before we moved from `latest` to `version` tags, these recipes were meant to be compatible with newer and older runtimes, some of which would not support Ubuntu 20.04 and jdk 11. Now that we have versions, there's nothing concrete stopping up from updating the latest recipes, although we need to dedicate some engineering time to do it :) Since these are meant to be guiding examples, feel free to modify them to Ubuntu 20.04 for your own images.
